name: Semantic Commit Check

on:
  workflow_dispatch:
    inputs:
      number:
        description: "Pull Request Number"
        required: true

jobs:
  main:
    name: Lint commit messages
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - run: echo "PR number -> ${{ github.event.inputs.number }}"
      - uses: wagoid/commitlint-github-action@v4
        with:
          route: GET /repos/{owner}/{repo}/pulls/{pull_number}
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          pull_number: ${{ github.event.inputs.number }}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
