name: PR checks

on: pull_request

jobs:
  trigger-semantic-pull-request:
    # should only run when not a fork
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        id: dispatch_semantic_pull_request
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          workflow_id: "semantic-pull-request.yml"
          ref: "master"
          inputs: '{"number": "${{ github.event.pull_request.number }}"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
