name: Lint Commit Messages

on: 
  workflow_dispatch:
    inputs:
      number:
        description: "Pull Request Number"
        required: true

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
    - id: get_pull
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/{owner}/{repo}/pulls/{pull_number}
        owner: ${{ github.event.repository.owner.login }}
        repo: ${{ github.event.repository.name }}
        pull_number: ${{ github.event.inputs.number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - id: checkout_pr
      uses: actions/checkout@v3
      with:
        ref: "refs/pull/${{ github.event.inputs.number }}/head"
        fetch-depth: 0
    - id: setup_node
      uses: actions/setup-node@v1
      with:
        node-version: ">=14.16.0 14"
    - id: install_dependencies
      run: npm install
    - id: lint_commits
      run: |
        stopMarker=$(uuidgen)
        echo "::stop-commands::$stopMarker"
        npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
        
