name: Lint Commit Messages

on: 
  workflow_dispatch:
    inputs:
      number:
        description: "Pull Request Number"
        required: true

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - id: get_pull
        run: echo "PR number -> ${{ github.event.inputs.number }}"
      - id: checkout_pr
        run: echo "checking out"
      - id: lint_commits
        run: echo "linting commits1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
