name: Semantic Pull Request

on:
  workflow_dispatch:
    inputs:
      number:
        description: "Pull Request Number"
        required: true

jobs:
  main:
    name: Semantic Pull Request
    runs-on: ubuntu-latest
    
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
