name: Lint Commit Messages

on: pull_request

jobs:
  commitlint:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - id: checkout_pr
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: lint_commits
        uses: wagoid/commitlint-github-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
