name: CI

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ">=16.16.0 16"
      - run: npm ci
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [">=14.16.0 14", ">=16.16.0 16"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.version }}
      - run: npm ci
